[package]
name = "utils"
version = "0.5.0"
edition = "2021"

[dependencies]
ahash = "0.7.6"
glam = { version = "0.20.2", features = ["rand"] }
serde = { version = "1.0.137", features = ["derive"] }

soa_derive = { path = "../soa_derive" }

[dev-dependencies]
rand = "0.8.5"