extends Object
class_name Layers

const TEAM_OFFSET := 7

const HULL_SHIP := 1
const HULL_MISSILE := 1 << 1
const HULL_FIGHTER := 1 << 2
const PROJECTILE := 1 << 3
#const DETECTOR_LARGE := 1 << 4
#const DETECTOR_SMALL := 1 << 5
const UNUSED_0 := 1 << 6

const TEAM := 0b0111_1111

const HULL := HULL_SHIP | HULL_MISSILE | HULL_FIGHTER
const ALL_HULL := (
		HULL
	| HULL << TEAM_OFFSET
	| HULL << TEAM_OFFSET * 2
	| HULL << TEAM_OFFSET * 3)

const HULL_SMALL := HULL_MISSILE | HULL_FIGHTER
const ALL_HULL_SMALL := (
		HULL_SMALL
	| HULL_SMALL << TEAM_OFFSET
	| HULL_SMALL << TEAM_OFFSET * 2
	| HULL_SMALL << TEAM_OFFSET * 3)

const ALL_HULL_SHIP := (
		HULL_SHIP
	| HULL_SHIP << TEAM_OFFSET
	| HULL_SHIP << TEAM_OFFSET * 2
	| HULL_SHIP << TEAM_OFFSET * 3)

const ALL_TEAM := (
	TEAM
	| TEAM << TEAM_OFFSET
	| TEAM << TEAM_OFFSET * 2
	| TEAM << TEAM_OFFSET * 3)


const DEBRIS := 1 << 28
const UNUSED_1 := 1 << 29
const UNUSED_2 := 1 << 30
const UNUSED_3 := 1 << 31

const ALL_NOT_TEAMED := DEBRIS | UNUSED_1 | UNUSED_2 | UNUSED_3




