use crate::prelude::*;

#[derive(Debug, Copy, Clone, PartialEq, Hash, Eq, Serialize, Deserialize)]
pub enum MouseButtonSerde {
    Right,
    Left,
    Middle,
    Unknown,
}

impl MouseButtonSerde {
    pub fn from_mouse_button(mouse_button: MouseButton) -> Self {
        match mouse_button {
            MouseButton::Right => Self::Right,
            MouseButton::Left => Self::Left,
            MouseButton::Middle => Self::Middle,
            MouseButton::Unknown => Self::Unknown,
        }
    }
}

impl Into<MouseButton> for MouseButtonSerde {
    fn into(self) -> MouseButton {
        match self {
            MouseButtonSerde::Right => MouseButton::Right,
            MouseButtonSerde::Left => MouseButton::Left,
            MouseButtonSerde::Middle => MouseButton::Middle,
            MouseButtonSerde::Unknown => MouseButton::Unknown,
        }
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Hash, Eq, Serialize, Deserialize)]
pub enum KeyCodeSerde {
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Semicolon,
    Equal,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    World1,
    World2,
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDecimal,
    KpDivide,
    KpMultiply,
    KpSubtract,
    KpAdd,
    KpEnter,
    KpEqual,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,
    Unknown,
}

impl KeyCodeSerde {
    pub fn from_key_code(key_code: KeyCode) -> Self {
        match key_code {
            KeyCode::Space => Self::Space,
            KeyCode::Apostrophe => Self::Apostrophe,
            KeyCode::Comma => Self::Comma,
            KeyCode::Minus => Self::Minus,
            KeyCode::Period => Self::Period,
            KeyCode::Slash => Self::Slash,
            KeyCode::Key0 => Self::Key0,
            KeyCode::Key1 => Self::Key1,
            KeyCode::Key2 => Self::Key2,
            KeyCode::Key3 => Self::Key3,
            KeyCode::Key4 => Self::Key4,
            KeyCode::Key5 => Self::Key5,
            KeyCode::Key6 => Self::Key6,
            KeyCode::Key7 => Self::Key7,
            KeyCode::Key8 => Self::Key8,
            KeyCode::Key9 => Self::Key9,
            KeyCode::Semicolon => Self::Semicolon,
            KeyCode::Equal => Self::Equal,
            KeyCode::A => Self::A,
            KeyCode::B => Self::B,
            KeyCode::C => Self::C,
            KeyCode::D => Self::D,
            KeyCode::E => Self::E,
            KeyCode::F => Self::F,
            KeyCode::G => Self::G,
            KeyCode::H => Self::H,
            KeyCode::I => Self::I,
            KeyCode::J => Self::J,
            KeyCode::K => Self::K,
            KeyCode::L => Self::L,
            KeyCode::M => Self::M,
            KeyCode::N => Self::N,
            KeyCode::O => Self::O,
            KeyCode::P => Self::P,
            KeyCode::Q => Self::Q,
            KeyCode::R => Self::R,
            KeyCode::S => Self::S,
            KeyCode::T => Self::T,
            KeyCode::U => Self::U,
            KeyCode::V => Self::V,
            KeyCode::W => Self::W,
            KeyCode::X => Self::X,
            KeyCode::Y => Self::Y,
            KeyCode::Z => Self::Z,
            KeyCode::LeftBracket => Self::LeftBracket,
            KeyCode::Backslash => Self::Backslash,
            KeyCode::RightBracket => Self::RightBracket,
            KeyCode::GraveAccent => Self::GraveAccent,
            KeyCode::World1 => Self::World1,
            KeyCode::World2 => Self::World2,
            KeyCode::Escape => Self::Escape,
            KeyCode::Enter => Self::Enter,
            KeyCode::Tab => Self::Tab,
            KeyCode::Backspace => Self::Backspace,
            KeyCode::Insert => Self::Insert,
            KeyCode::Delete => Self::Delete,
            KeyCode::Right => Self::Right,
            KeyCode::Left => Self::Left,
            KeyCode::Down => Self::Down,
            KeyCode::Up => Self::Up,
            KeyCode::PageUp => Self::PageUp,
            KeyCode::PageDown => Self::PageDown,
            KeyCode::Home => Self::Home,
            KeyCode::End => Self::End,
            KeyCode::CapsLock => Self::CapsLock,
            KeyCode::ScrollLock => Self::ScrollLock,
            KeyCode::NumLock => Self::NumLock,
            KeyCode::PrintScreen => Self::PrintScreen,
            KeyCode::Pause => Self::Pause,
            KeyCode::F1 => Self::F1,
            KeyCode::F2 => Self::F2,
            KeyCode::F3 => Self::F3,
            KeyCode::F4 => Self::F4,
            KeyCode::F5 => Self::F5,
            KeyCode::F6 => Self::F6,
            KeyCode::F7 => Self::F7,
            KeyCode::F8 => Self::F8,
            KeyCode::F9 => Self::F9,
            KeyCode::F10 => Self::F10,
            KeyCode::F11 => Self::F11,
            KeyCode::F12 => Self::F12,
            KeyCode::F13 => Self::F13,
            KeyCode::F14 => Self::F14,
            KeyCode::F15 => Self::F15,
            KeyCode::F16 => Self::F16,
            KeyCode::F17 => Self::F17,
            KeyCode::F18 => Self::F18,
            KeyCode::F19 => Self::F19,
            KeyCode::F20 => Self::F20,
            KeyCode::F21 => Self::F21,
            KeyCode::F22 => Self::F22,
            KeyCode::F23 => Self::F23,
            KeyCode::F24 => Self::F24,
            KeyCode::F25 => Self::F25,
            KeyCode::Kp0 => Self::Kp0,
            KeyCode::Kp1 => Self::Kp1,
            KeyCode::Kp2 => Self::Kp2,
            KeyCode::Kp3 => Self::Kp3,
            KeyCode::Kp4 => Self::Kp4,
            KeyCode::Kp5 => Self::Kp5,
            KeyCode::Kp6 => Self::Kp6,
            KeyCode::Kp7 => Self::Kp7,
            KeyCode::Kp8 => Self::Kp8,
            KeyCode::Kp9 => Self::Kp9,
            KeyCode::KpDecimal => Self::KpDecimal,
            KeyCode::KpDivide => Self::KpDivide,
            KeyCode::KpMultiply => Self::KpMultiply,
            KeyCode::KpSubtract => Self::KpSubtract,
            KeyCode::KpAdd => Self::KpAdd,
            KeyCode::KpEnter => Self::KpEnter,
            KeyCode::KpEqual => Self::KpEqual,
            KeyCode::LeftShift => Self::LeftShift,
            KeyCode::LeftControl => Self::LeftControl,
            KeyCode::LeftAlt => Self::LeftAlt,
            KeyCode::LeftSuper => Self::LeftSuper,
            KeyCode::RightShift => Self::RightShift,
            KeyCode::RightControl => Self::RightControl,
            KeyCode::RightAlt => Self::RightAlt,
            KeyCode::RightSuper => Self::RightSuper,
            KeyCode::Menu => Self::Menu,
            KeyCode::Unknown => Self::Unknown,
        }
    }
}

impl Into<KeyCode> for KeyCodeSerde {
    fn into(self) -> KeyCode {
        match self {
            KeyCodeSerde::Space => KeyCode::Space,
            KeyCodeSerde::Apostrophe => KeyCode::Apostrophe,
            KeyCodeSerde::Comma => KeyCode::Comma,
            KeyCodeSerde::Minus => KeyCode::Minus,
            KeyCodeSerde::Period => KeyCode::Period,
            KeyCodeSerde::Slash => KeyCode::Slash,
            KeyCodeSerde::Key0 => KeyCode::Key0,
            KeyCodeSerde::Key1 => KeyCode::Key1,
            KeyCodeSerde::Key2 => KeyCode::Key2,
            KeyCodeSerde::Key3 => KeyCode::Key3,
            KeyCodeSerde::Key4 => KeyCode::Key4,
            KeyCodeSerde::Key5 => KeyCode::Key5,
            KeyCodeSerde::Key6 => KeyCode::Key6,
            KeyCodeSerde::Key7 => KeyCode::Key7,
            KeyCodeSerde::Key8 => KeyCode::Key8,
            KeyCodeSerde::Key9 => KeyCode::Key9,
            KeyCodeSerde::Semicolon => KeyCode::Semicolon,
            KeyCodeSerde::Equal => KeyCode::Equal,
            KeyCodeSerde::A => KeyCode::A,
            KeyCodeSerde::B => KeyCode::B,
            KeyCodeSerde::C => KeyCode::C,
            KeyCodeSerde::D => KeyCode::D,
            KeyCodeSerde::E => KeyCode::E,
            KeyCodeSerde::F => KeyCode::F,
            KeyCodeSerde::G => KeyCode::G,
            KeyCodeSerde::H => KeyCode::H,
            KeyCodeSerde::I => KeyCode::I,
            KeyCodeSerde::J => KeyCode::J,
            KeyCodeSerde::K => KeyCode::K,
            KeyCodeSerde::L => KeyCode::L,
            KeyCodeSerde::M => KeyCode::M,
            KeyCodeSerde::N => KeyCode::N,
            KeyCodeSerde::O => KeyCode::O,
            KeyCodeSerde::P => KeyCode::P,
            KeyCodeSerde::Q => KeyCode::Q,
            KeyCodeSerde::R => KeyCode::R,
            KeyCodeSerde::S => KeyCode::S,
            KeyCodeSerde::T => KeyCode::T,
            KeyCodeSerde::U => KeyCode::U,
            KeyCodeSerde::V => KeyCode::V,
            KeyCodeSerde::W => KeyCode::W,
            KeyCodeSerde::X => KeyCode::X,
            KeyCodeSerde::Y => KeyCode::Y,
            KeyCodeSerde::Z => KeyCode::Z,
            KeyCodeSerde::LeftBracket => KeyCode::LeftBracket,
            KeyCodeSerde::Backslash => KeyCode::Backslash,
            KeyCodeSerde::RightBracket => KeyCode::RightBracket,
            KeyCodeSerde::GraveAccent => KeyCode::GraveAccent,
            KeyCodeSerde::World1 => KeyCode::World1,
            KeyCodeSerde::World2 => KeyCode::World2,
            KeyCodeSerde::Escape => KeyCode::Escape,
            KeyCodeSerde::Enter => KeyCode::Enter,
            KeyCodeSerde::Tab => KeyCode::Tab,
            KeyCodeSerde::Backspace => KeyCode::Backspace,
            KeyCodeSerde::Insert => KeyCode::Insert,
            KeyCodeSerde::Delete => KeyCode::Delete,
            KeyCodeSerde::Right => KeyCode::Right,
            KeyCodeSerde::Left => KeyCode::Left,
            KeyCodeSerde::Down => KeyCode::Down,
            KeyCodeSerde::Up => KeyCode::Up,
            KeyCodeSerde::PageUp => KeyCode::PageUp,
            KeyCodeSerde::PageDown => KeyCode::PageDown,
            KeyCodeSerde::Home => KeyCode::Home,
            KeyCodeSerde::End => KeyCode::End,
            KeyCodeSerde::CapsLock => KeyCode::CapsLock,
            KeyCodeSerde::ScrollLock => KeyCode::ScrollLock,
            KeyCodeSerde::NumLock => KeyCode::NumLock,
            KeyCodeSerde::PrintScreen => KeyCode::PrintScreen,
            KeyCodeSerde::Pause => KeyCode::Pause,
            KeyCodeSerde::F1 => KeyCode::F1,
            KeyCodeSerde::F2 => KeyCode::F2,
            KeyCodeSerde::F3 => KeyCode::F3,
            KeyCodeSerde::F4 => KeyCode::F4,
            KeyCodeSerde::F5 => KeyCode::F5,
            KeyCodeSerde::F6 => KeyCode::F6,
            KeyCodeSerde::F7 => KeyCode::F7,
            KeyCodeSerde::F8 => KeyCode::F8,
            KeyCodeSerde::F9 => KeyCode::F9,
            KeyCodeSerde::F10 => KeyCode::F10,
            KeyCodeSerde::F11 => KeyCode::F11,
            KeyCodeSerde::F12 => KeyCode::F12,
            KeyCodeSerde::F13 => KeyCode::F13,
            KeyCodeSerde::F14 => KeyCode::F14,
            KeyCodeSerde::F15 => KeyCode::F15,
            KeyCodeSerde::F16 => KeyCode::F16,
            KeyCodeSerde::F17 => KeyCode::F17,
            KeyCodeSerde::F18 => KeyCode::F18,
            KeyCodeSerde::F19 => KeyCode::F19,
            KeyCodeSerde::F20 => KeyCode::F20,
            KeyCodeSerde::F21 => KeyCode::F21,
            KeyCodeSerde::F22 => KeyCode::F22,
            KeyCodeSerde::F23 => KeyCode::F23,
            KeyCodeSerde::F24 => KeyCode::F24,
            KeyCodeSerde::F25 => KeyCode::F25,
            KeyCodeSerde::Kp0 => KeyCode::Kp0,
            KeyCodeSerde::Kp1 => KeyCode::Kp1,
            KeyCodeSerde::Kp2 => KeyCode::Kp2,
            KeyCodeSerde::Kp3 => KeyCode::Kp3,
            KeyCodeSerde::Kp4 => KeyCode::Kp4,
            KeyCodeSerde::Kp5 => KeyCode::Kp5,
            KeyCodeSerde::Kp6 => KeyCode::Kp6,
            KeyCodeSerde::Kp7 => KeyCode::Kp7,
            KeyCodeSerde::Kp8 => KeyCode::Kp8,
            KeyCodeSerde::Kp9 => KeyCode::Kp9,
            KeyCodeSerde::KpDecimal => KeyCode::KpDecimal,
            KeyCodeSerde::KpDivide => KeyCode::KpDivide,
            KeyCodeSerde::KpMultiply => KeyCode::KpMultiply,
            KeyCodeSerde::KpSubtract => KeyCode::KpSubtract,
            KeyCodeSerde::KpAdd => KeyCode::KpAdd,
            KeyCodeSerde::KpEnter => KeyCode::KpEnter,
            KeyCodeSerde::KpEqual => KeyCode::KpEqual,
            KeyCodeSerde::LeftShift => KeyCode::LeftShift,
            KeyCodeSerde::LeftControl => KeyCode::LeftControl,
            KeyCodeSerde::LeftAlt => KeyCode::LeftAlt,
            KeyCodeSerde::LeftSuper => KeyCode::LeftSuper,
            KeyCodeSerde::RightShift => KeyCode::RightShift,
            KeyCodeSerde::RightControl => KeyCode::RightControl,
            KeyCodeSerde::RightAlt => KeyCode::RightAlt,
            KeyCodeSerde::RightSuper => KeyCode::RightSuper,
            KeyCodeSerde::Menu => KeyCode::Menu,
            KeyCodeSerde::Unknown => KeyCode::Unknown,
        }
    }
}
