[package]
name = "headless_server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.17", features = ["release_max_level_info"] }
tui-logger = "0.8.0"
termion = "1.5.6"
tui = { version = "0.18.0", default-features = false, features = ['termion'] }

common = { path = "../common" }
battlescape = { path = "../battlescape"}
utils = { path = "../utils/utils" }
soa_derive = { path = "../utils/soa_derive" }
metascape = { path = "../metascape" }

ahash = "0.7.6"
crc32fast = { version = "1.3.2", features = ["nightly"] }
bytemuck = { version = "1.10.0", features = [ "derive" ] }

num_enum = "0.5.7"

serde = { version = "1.0.138", features = ["derive"] }
bincode = "1.3.3"

glam = { version = "0.21.2", features = ["serde", "rand"] }

rayon = "1.5.3"
tokio = { version = "1.19.2", features = ["full"] }
reqwest = { version = "0.11.11", features = ["json"] }

crossbeam = "0.8.1"

