[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rapier2d = { version = "0.17", features = [ "simd-nightly", "serde-serialize" ] }

tokio = { version = "1.26", features = [ "full" ] }
tokio-tungstenite = { version = "0.18", features = [ "native-tls" ] }
futures-util = "0.3"

rayon = "1.7"
crossbeam = "0.8"
parking_lot = "0.12"

serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"
# crc32fast = "1.3.2"
bytes = "1.4"

log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
anyhow = "1.0"

ahash = { version = "0.8", features = ["serde"] }
smallvec = { version = "1.10", features = ["union", "serde"] }

rand = "0.8"
rand_xoshiro = { version = "0.6", features = ["serde1"] }

[profile.release]
lto = "thin"