[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.14", features = ["release_max_level_info"] }
tui-logger = "0.6.5"
termion = "1.5.6"
tui = { version = "0.16", default-features = false, features = ['termion'] }

# steamworks = { git = "https://github.com/Noxime/steamworks-rs.git", rev = "5e9ac5eef942edc40c0473d23df8834acaf0c8e5" }

common = { path = "../common" }

bevy_ecs = "0.5.0"
bevy_tasks = "0.5.0"

ahash = "0.7.6"
indexmap = {version = "1.7.0", features = ["serde"] }

num_enum = "0.5.4"

serde = { version = "1.0.132", features = ["derive"] }
bincode = "1.3.3"
# serde_yaml = "0.8.21"
# serde_json = "1.0.69"

rand = { version = "0.8.4", features = ["nightly", "simd_support"] }
rand_xoshiro = "0.6.0"

glam = { version = "0.20.2", features = ["serde", "rand"] }
# bytes = "1.1.0"

tokio = { version = "1.15.0", features = ["full"] }
# reqwest = { version = "0.11.6", features = ["json"] }

crossbeam-channel = "0.5.1"
crossbeam-queue = "0.3.2"
# rayon = "1.5.1"