[package]
name = "battlescape"
version = "0.1.0"
authors = ["indubitablement2 <jeanmichel88@hotmail.com>"]
edition = "2021"

[dependencies]
log = { version = "0.4.14", features = ["release_max_level_off"] }

common = { path = "../common" }

rand = { version = "0.8.5", features = ["nightly", "simd_support"] }
rand_xoshiro = {version = "0.6.0", features = ["serde1"]}
weighted_rand = "0.3.2"

crossbeam = "0.8.1"

ahash = "0.7.6"

serde = { version = "1.0.138", features = ["derive"] }
bincode = "1.3.3"

# Physic and deterministic math.
nalgebra = { version = "0.31.0", features = ["libm-force", "serde-serialize"] }
rapier2d = { version = "0.13.0", features = ["enhanced-determinism", "serde-serialize"] }
