[package]
name = "battlescape"
version = "0.1.0"
authors = ["indubitablement2 <jeanmichel88@hotmail.com>"]
edition = "2021"

[dependencies]
log = { version = "0.4.14", features = ["release_max_level_warn"] }

# common = { path = "../common" }

num_enum = "0.5.7"

rand = { version = "0.8.4", features = ["nightly", "simd_support"] }
rand_xoshiro = {version = "0.6.0", features = ["serde1"]}

crossbeam = "0.8.1"
# parking_lot = "0.11.2"

ahash = {version = "0.7.6", features = ["serde"]}
indexmap = {version = "1.8.0", features = ["serde"] }

serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"
serde_yaml = "0.8.23"

# Physic and deterministic math.
nalgebra = { version = "0.29.0", features = ["libm-force", "serde-serialize"] }
rapier2d = { version = "0.11.1", features = ["enhanced-determinism", "serde-serialize"] }
