[package]
name = "common"
version = "0.3.0"
edition = "2021"

[dependencies]
log = { version = "0.4.17" }

serde = { version = "1.0.138", features = ["derive"] }
bincode = "1.3.3"

nalgebra = { version = "0.31.1", features = ["serde-serialize", "libm-force"] }

ahash = {version = "0.7.6", features = ["serde"] }

rand = { version = "0.8.5", features = ["nightly", "simd_support"] }

tokio = { version = "1.19.2", features = ["full"] }
crossbeam = "0.8.1"

bytemuck = { version = "1.10.0", features = [ "derive" ] }

utils = { path = "../utils/utils" }
acc = { path = "../acc" }