[package]
name = "common"
version = "0.3.0"
edition = "2021"

[dependencies]
log = { version = "0.4.14" }

battlescape = { path = "../battlescape"}

serde = { version = "1.0.136", features = ["derive"] }
bincode = "1.3.3"
serde_yaml = "0.8.23"
# serde_json = "1.0.69"

glam = { version = "0.20.2", features = ["serde", "rand"] }
# bytes = "1.1.0"

ahash = {version = "0.7.6", features = ["serde"] }
# indexmap = {version = "1.7.0", features = ["serde"] }

rand = { version = "0.8.4", features = ["nightly", "simd_support"] }
rand_xoshiro = "0.6.0"

tokio = { version = "1.16.1", features = ["full"] }
crossbeam = "0.8.1"

utils = { path = "../../utils/utils" }