[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.14", features = ["release_max_level_off"] }

bevy_ecs = "0.5.0"
bevy_tasks = "0.5.0"

rand = { version = "0.8.4", features = ["nightly", "simd_support"] }
rand_xoshiro = "0.6.0"

ahash = "0.7.6"
indexmap = {version = "1.7.0", features = ["serde"] }

num_enum = "0.5.4"

serde = { version = "1.0.130", features = ["derive"] }
bincode = "1.3.3"
# serde_yaml = "0.8.21"
# serde_json = "1.0.69"

# rapier2d = { version = "0.11.1", features = ["serde-serialize"] }
# nalgebra = { version = "0.29.0", features = ["serde-serialize"] }

glam = { version = "0.20.0", features = ["serde", "rand"] }
# bytes = "1.1.0"

crossbeam-channel = "0.5.1"
rayon = "1.5.1"

tokio = { version = "1.13.0", features = ["full"] }
# reqwest = { version = "0.11.6", features = ["json"] }
