[package]
name = "soa_derive_debug"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0.96", features = ["full", "extra-traits"] }
quote = "1.0.18"
proc-macro2 = "1.0.39"
utils = { path = "../utils" }
