#ifndef GODOT_CUSTOM_CLIENT_REGISTER_TYPES_H
#define GODOT_CUSTOM_CLIENT_REGISTER_TYPES_H

#include "modules/register_module_types.h"

void initialize_godot_custom_client_module(ModuleInitializationLevel p_level);
void uninitialize_godot_custom_client_module(ModuleInitializationLevel p_level);

#endif
